# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0015_idtoken_acr'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='jwks_uri',
            field=models.URLField(blank=True, max_length=2048, verbose_name='JSON Web Keys uri'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('web', 'Web Application'), ('javascript', 'Javascript Application'), ('native', 'Native Application'), ('service', 'Service Account'), ('trusted', 'Trusted Client')], default='web', max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='check_session_iframe',
            field=models.URLField(blank=True, default='', max_length=2048, verbose_name='check_session_iframe uri'),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='picture_endpoint',
            field=models.URLField(blank=True, default='', max_length=2048, verbose_name='picture uri'),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='profile_uri',
            field=models.URLField(blank=True, default='', max_length=2048, verbose_name='uri for HTML View to change the profile'),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='uri',
            field=models.URLField(blank=True, default='', max_length=2048, verbose_name='Home url'),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='user_navigation_uri',
            field=models.URLField(blank=True, default='', max_length=2048, verbose_name='user navigation uri'),
        ),
        migrations.AlterField(
            model_name='idtoken',
            name='acr',
            field=models.TextField(blank=True, default='', verbose_name='Authentication Context Class Reference'),
        ),
        migrations.AlterField(
            model_name='idtoken',
            name='raw',
            field=models.TextField(blank=True, default='', verbose_name='raw content'),
        ),
        migrations.AlterField(
            model_name='idtoken',
            name='session_state',
            field=models.TextField(blank=True, default='', verbose_name='session state'),
        ),
    ]
