# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0017_remove_identityprovider_certs_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='is_secure',
            field=models.BooleanField(default=True, verbose_name='is secure'),
        ),
    ]
