# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-10 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0018_identityprovider_is_secure'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='check_roles',
            field=models.BooleanField(default=False, verbose_name='check roles'),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='extend_access_uri',
            field=models.URLField(blank=True, default='', max_length=2048, verbose_name='extend access uri'),
        ),
    ]
