# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0019_auto_20180510_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='acr_values',
            field=models.CharField(blank=True, max_length=255, verbose_name='acr_values'),
        ),
        migrations.AddField(
            model_name='client',
            name='claims',
            field=models.TextField(blank=True, verbose_name='claims'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_age',
            field=models.DurationField(blank=True, null=True, verbose_name='max_age'),
        ),
    ]
