# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0020_auto_20180522_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeVerifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, default=functools.partial(django.utils.crypto.get_random_string, *(), **{'length': 128}), max_length=128, verbose_name='value')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth2.Client')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
