# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0021_codeverifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='use_pkce',
            field=models.BooleanField(default=False, verbose_name='use PKCE'),
        ),
    ]
