# Generated by Django 2.0.7 on 2018-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0024_client_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='redirect_uri',
            field=models.CharField(blank=True, default='/oauth2/login/', max_length=2048, verbose_name='redirect uri'),
        ),
    ]
