# Generated by Django 2.1 on 2018-08-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0025_client_redirect_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='claims_locales',
            field=models.CharField(blank=True, help_text='See http://openid.net/specs/openid-connect-core-1_0.html#ClaimsLanguagesAndScripts', max_length=255, verbose_name='claims locales'),
        ),
        migrations.AddField(
            model_name='client',
            name='ui_locales',
            field=models.CharField(blank=True, help_text='See http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest', max_length=255, verbose_name='ui locales'),
        ),
    ]
