# Generated by Django 2.1 on 2018-08-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0026_auto_20180817_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prompt',
            field=models.CharField(blank=True, help_text='See http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest', max_length=255, verbose_name='prompt'),
        ),
    ]
