# Generated by Django 2.2.9 on 2020-01-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0027_client_prompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['identity_provider', 'name']},
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(max_length=4096, verbose_name='token'),
        ),
    ]
