# Generated by Django 2.2.9 on 2020-01-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0030_auto_20200119_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.TextField(verbose_name='token'),
        ),
    ]
