# Generated by Django 2.2.9 on 2020-01-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0031_auto_20200119_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.TextField(verbose_name='token'),
        ),
    ]
