# Generated by Django 2.2.12 on 2020-06-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0032_auto_20200119_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(max_length=255, verbose_name='uuid'),
        ),
    ]
