# Generated by Django 2.2.12 on 2020-06-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0033_auto_20200601_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='roles_claim',
            field=models.CharField(blank=True, max_length=255, verbose_name='name of the roles_claim'),
        ),
    ]
