# Generated by Django 3.2.16 on 2022-10-11 18:21

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0035_auto_20210131_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonce',
            name='value',
            field=models.CharField(db_index=True, default=functools.partial(django.utils.crypto.get_random_string, *(), **{'length': 12}), max_length=12, verbose_name='value'),
        ),
    ]
