# Generated by Django 5.2.4 on 2025-08-01 09:17

import client.oauth2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0036_alter_nonce_value'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', client.oauth2.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='kc_idp_hint',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Keycloak kc_idp_hint param'),
        ),
    ]
